"""Targeted CPU tests; importing this file never imports an Isaac package.

Run directly with the project's Python. Temporary fixture copies are deleted by
TemporaryDirectory; no production derived asset is generated by these tests.
"""

import argparse
import ast
import csv
import hashlib
import io
import importlib.util
import json
import math
import os
from pathlib import Path
import shutil
import sys
import tempfile
import unittest
from unittest import mock
import xml.etree.ElementTree as ET

import numpy as np


REPO_ROOT = Path(__file__).resolve().parents[3]
SPEC = importlib.util.spec_from_file_location("_cr12_asset_math", REPO_ROOT / "scripts/environments/_cr12_asset_math.py")
asset = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(asset)
DRIVE_SPEC = importlib.util.spec_from_file_location("_cr12_drive_checks", REPO_ROOT / "scripts/environments/run_cr12_joint_drive.py")
drive = importlib.util.module_from_spec(DRIVE_SPEC)
DRIVE_SPEC.loader.exec_module(drive)
HOLD_SPEC = importlib.util.spec_from_file_location("_cr12_hold_diagnostics", REPO_ROOT / "scripts/environments/_cr12_hold_diagnostics.py")
hold = importlib.util.module_from_spec(HOLD_SPEC)
HOLD_SPEC.loader.exec_module(hold)


class AssetMathTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.real = asset.analyze_source()
        cls.temp = tempfile.TemporaryDirectory(prefix="cr12_cpu_test_")
        cls.fixture = Path(cls.temp.name) / "rokeaCR12"
        (cls.fixture / "model").mkdir(parents=True)
        cls.source = cls.fixture / "rokea_cr12_7DOF.urdf"
        root = ET.parse(asset.DEFAULT_SOURCE_URDF).getroot()
        for mesh in root.findall(".//mesh"):
            source = Path(mesh.get("filename"))
            destination = cls.fixture / "model" / source.name
            shutil.copyfile(source, destination)
            mesh.set("filename", str(destination))
        ET.ElementTree(root).write(cls.source, encoding="utf-8", xml_declaration=True)
        # Only the test fixture's URDF differs (absolute filenames). Mesh hashes,
        # numeric approval constants, and every production check remain active.
        cls.hash_patch = mock.patch.dict(asset.APPROVED_SOURCE_HASHES, {
            "rokea_cr12_7DOF.urdf": hashlib.sha256(cls.source.read_bytes()).hexdigest()
        })
        cls.hash_patch.start()

    @classmethod
    def tearDownClass(cls):
        cls.hash_patch.stop()
        cls.temp.cleanup()

    def output(self, name):
        return self.fixture / "derived" / name / "cr12_fixed_lift0.urdf"

    def test_real_inputs_and_independent_reviewed_constants(self):
        self.assertEqual(len(self.real["source_hashes"]), 21)
        self.assertEqual(sum(not value["triangle_valid"] for value in self.real["original"].values()), 8)
        self.assertTrue(all(value["positive_definite"] for value in self.real["original"].values()))
        self.assertEqual(self.real["bodies"]["agv"]["mass"], 63.44074938)
        self.assertEqual(self.real["bodies"]["link_6"]["mass"], 3.652558753)
        self.assertAlmostEqual(sum(body["mass"] for body in self.real["bodies"].values()), 82.860365324, places=11)
        np.testing.assert_allclose(self.real["candidates"]["scanner"]["com"],
                                   [-.000017059325, -.129429244995, .192403900145], atol=1e-14, rtol=0)
        np.testing.assert_allclose(self.real["bodies"]["agv"]["com"],
                                   [.009847509526981598, .0006037831298602024, .6100607573843], atol=1e-14, rtol=0)
        np.testing.assert_allclose(self.real["bodies"]["link_6"]["inertia3x3"],
                                   [[.09761583941767576, -.00912286701490933, -.016382306980800274],
                                    [-.00912286701490933, .09762701393460375, -.01636653580809325],
                                    [-.016382306980800274, -.01636653580809325, .056319554644805946]], atol=1e-14, rtol=0)
        json.dumps(self.real, allow_nan=False)

    def test_box_and_rotation_parallel_axis_independent_quadrature(self):
        components = [self.real["candidates"][name] for name in ("link_6", "scanner")]
        signs = np.array([[x, y, z] for x in (-1, 1) for y in (-1, 1) for z in (-1, 1)])
        points, weights = [], []
        for body, rotation in zip(components, (np.eye(3), asset.rpy_matrix([0, 0, 3*math.pi/4]))):
            points.extend((np.asarray(body["com"]) + signs*np.asarray(body["size"])/(2*math.sqrt(3))) @ rotation.T)
            weights.extend([body["mass"]/8]*8)
        points, weights = np.array(points), np.array(weights)
        center = (points*weights[:, None]).sum(axis=0)/weights.sum()
        centered = points-center
        covariance = centered.T@(centered*weights[:, None])
        independent = np.trace(covariance)*np.eye(3)-covariance
        np.testing.assert_allclose(independent, self.real["bodies"]["link_6"]["inertia3x3"], atol=1e-14, rtol=0)
        with self.assertRaises(ValueError):
            asset.box_properties(1, [0, 0, 0], [1, 0, 1])

    def test_geometry_bounds_transform_vertices_not_box_corners(self):
        mesh = Path(self.temp.name) / "bounds_fixture.obj"
        mesh.write_text("v 0 0 0\nv 1000 0 1000\nv 0 2000 2000\nf 1 2 3\n", encoding="ascii")
        lo, hi = asset.geometry_body_bounds({
            "filename": str(mesh), "scale": [.001]*3,
            "origin_rpy": [0, 0, math.pi/4], "origin_xyz": [3, 4, 5],
        })
        np.testing.assert_allclose(lo, [3-math.sqrt(2), 4, 5], atol=1e-14, rtol=0)
        np.testing.assert_allclose(hi, [3+1/math.sqrt(2), 4+math.sqrt(2), 7], atol=1e-14, rtol=0)

    def test_generation_structure_geometries_limits_and_source_protection(self):
        before = asset.source_fingerprint(self.source)
        output = self.output("valid")
        result = asset.generate_urdf(self.source, output)
        root = ET.parse(output).getroot()
        self.assertEqual([node.get("name") for node in root.findall("link")], list(asset.BODY_NAMES))
        self.assertEqual([node.get("name") for node in root.findall("joint")], list(asset.JOINT_NAMES))
        self.assertTrue(all(node.get("type") == "revolute" for node in root.findall("joint")))
        self.assertEqual(len(root.findall(".//mesh")), 20)
        self.assertEqual(root.find("joint[@name='joint_1']/parent").get("link"), "agv")
        np.testing.assert_allclose([float(x) for x in root.find("joint[@name='joint_1']/origin").get("xyz").split()], [.105, 0, 1.062])
        scanner = root.find("link[@name='link_6']/collision[@name='scanner_collision']")
        self.assertAlmostEqual(float(scanner.find("origin").get("rpy").split()[2]), 3*math.pi/4, places=14)
        np.testing.assert_allclose(asset.validate_derived(output, self.source)["bodies"]["link_6"]["com"],
                                   [.06071267344171582, .06071821788515036, .11853282647734235], atol=1e-14)
        self.assertEqual(asset.source_fingerprint(self.source), before)
        self.assertEqual(result["derived_sha256"], hashlib.sha256(output.read_bytes()).hexdigest())
        with self.assertRaises(FileExistsError):
            asset.generate_urdf(self.source, output)
        with self.assertRaises(ValueError):
            asset.generate_urdf(self.source, self.source)

    def test_changed_original_is_rejected_without_output(self):
        original = self.source.read_bytes()
        output = self.output("changed_source")
        try:
            self.source.write_bytes(original+b"\n")
            with self.assertRaisesRegex(ValueError, "Approved source changed"):
                asset.generate_urdf(self.source, output)
            self.assertFalse(output.exists())
        finally:
            self.source.write_bytes(original)

    def test_existing_foreign_output_and_wrong_location_rejected(self):
        output = self.output("foreign")
        output.parent.mkdir(parents=True)
        output.write_bytes(b"existing user file")
        with self.assertRaises(FileExistsError):
            asset.generate_urdf(self.source, output)
        self.assertEqual(output.read_bytes(), b"existing user file")
        with self.assertRaises(ValueError):
            asset.generate_urdf(self.source, self.fixture / "wrong.urdf")

    def test_derived_tensor_geometry_and_joint_tampering_rejected(self):
        output = self.output("tampering")
        asset.generate_urdf(self.source, output)
        clean = output.read_bytes()
        mutations = [
            ("link[@name='link_6']/inertial/inertia", "ixy", "0"),
            ("link[@name='link_6']/visual[@name='scanner_visual']/origin", "rpy", "0 0 0"),
            ("joint[@name='joint_2']/limit", "effort", "301"),
            ("link[@name='agv']/collision/geometry/mesh", "scale", "1 1 1"),
        ]
        for selector, key, value in mutations:
            with self.subTest(selector=selector):
                root = ET.fromstring(clean)
                root.find(selector).set(key, value)
                ET.ElementTree(root).write(output, encoding="utf-8", xml_declaration=True)
                with self.assertRaises(ValueError):
                    asset.validate_derived(output, self.source)
        output.write_bytes(clean)

    def test_trajectory_segments_endpoints_and_reference_times(self):
        for t, expected in ((0, 0), (1, 0), (2, math.radians(2.5)), (3, math.radians(5)), (6, math.radians(5))):
            q, dq = asset.trajectory(t)
            self.assertAlmostEqual(q[1], expected, places=14)
            np.testing.assert_array_equal(np.delete(q, 1), np.zeros(5))
            if t != 2:
                np.testing.assert_array_equal(dq, np.zeros(6))
        self.assertAlmostEqual(asset.trajectory(2)[1][1], .0818123086872342, places=14)
        h = 1e-5
        finite_difference = (asset.trajectory(1.7+h)[0]-asset.trajectory(1.7-h)[0])/(2*h)
        np.testing.assert_allclose(finite_difference, asset.trajectory(1.7)[1], atol=1e-10, rtol=0)
        self.assertEqual(asset.step_reference_times(119), (119/120, 1))
        self.assertEqual(asset.step_reference_times(719), (719/120, 6))
        self.assertGreater(asset.trajectory(asset.step_reference_times(180)[1])[0][1], asset.trajectory(asset.step_reference_times(180)[0])[0][1])
        for invalid in (-1, 720, 1.5, True):
            with self.assertRaises(ValueError):
                asset.step_reference_times(invalid)
        for invalid in (-.1, 6.1, float("nan")):
            with self.assertRaises(ValueError):
                asset.trajectory(invalid)

    def test_native_name_mapping_and_quaternion_conventions(self):
        self.assertEqual(asset.name_indices(reversed(asset.JOINT_NAMES), asset.JOINT_NAMES), [5, 4, 3, 2, 1, 0])
        for actual in (("a", "a"), ("a",), ("a", "b", "c")):
            with self.assertRaises(ValueError):
                asset.name_indices(actual, ("a", "b"))
        angle = 3*math.pi/4
        wxyz = [math.cos(angle/2), 0, 0, math.sin(angle/2)]
        xyzw = wxyz[1:]+wxyz[:1]
        np.testing.assert_allclose(asset.quaternion_matrix(wxyz), asset.rpy_matrix([0, 0, angle]), atol=1e-14)
        np.testing.assert_allclose(asset.quaternion_matrix(xyzw, "xyzw"), asset.quaternion_matrix(wxyz), atol=1e-14)
        with self.assertRaises(ValueError):
            asset.quaternion_matrix([0, 0, 0, 0])

    def test_cpu_import_has_no_runtime_modules(self):
        self.assertFalse(any(name == "torch" or name == "pxr" or name.startswith(("isaaclab", "isaacsim", "omni.")) for name in sys.modules))

    def test_physx_full_tensor_does_not_rotate_principal_axes_twice(self):
        angle = math.pi/4
        xyzw = [0, 0, math.sin(angle/2), math.cos(angle/2)]
        # Independent hand calculation: Rz45 diag(2,3,4) Rz45.T.
        raw_body = np.array([[2.5, -.5, 0], [-.5, 2.5, 0], [0, 0, 4]])
        checked = asset.checked_physx_body_inertia(raw_body, xyzw, [2, 3, 4])
        np.testing.assert_array_equal(checked, raw_body)
        # The principal diagonal alone is not a body-axis tensor at this pose.
        with self.assertRaises(ValueError):
            asset.checked_physx_body_inertia(np.diag([2., 3., 4.]), xyzw, [2, 3, 4])
        with self.assertRaises(ValueError):
            asset.checked_physx_body_inertia(raw_body, xyzw, [2, 3, 5])

    def test_drive_no_progress_timing(self):
        zeros = [0.0]*6
        # The initial hold ending at t=1 must not trigger the ramp progress gate.
        drive.check_joint_sample(zeros, zeros, zeros, asset.JOINT_LIMITS, 1.0, None)
        # Isolate the progress gate; the real t=2 mathematical reference would
        # additionally fail the tracking gate for this stationary measurement.
        with self.assertRaises(drive.DriveCheckError) as caught:
            drive.check_joint_sample(zeros, zeros, zeros, asset.JOINT_LIMITS, 2.0, 0.0)
        self.assertEqual(caught.exception.category, "no_progress")
        q, dq = asset.trajectory(2.0)
        drive.check_joint_sample(q, dq, q, asset.JOINT_LIMITS, 2.0, 0.0)

    def test_drive_clock_rejects_extra_steps_and_invalid_time(self):
        drive.check_clock(10, 10*asset.DT, 11, 11*asset.DT, asset.DT)
        for step_after, time_after in ((12, 12*asset.DT), (11, 12*asset.DT), (11, float("nan"))):
            with self.subTest(step_after=step_after, time_after=time_after):
                with self.assertRaises(drive.DriveCheckError):
                    drive.check_clock(10, 10*asset.DT, step_after, time_after, asset.DT)

    def test_drive_last_second_speed_and_finite_state(self):
        q, _ = asset.trajectory(5.0)
        speed = [0.0]*6
        speed[1] = .02  # Below the global .25 limit, above the hold .01 limit.
        drive.check_joint_sample(q, speed, q, asset.JOINT_LIMITS, 4.99, 0.0)
        with self.assertRaisesRegex(drive.DriveCheckError, "Last-second"):
            drive.check_joint_sample(q, speed, q, asset.JOINT_LIMITS, 5.0, 0.0)
        q[0] = float("nan")
        with self.assertRaises(drive.DriveCheckError) as caught:
            drive.check_joint_sample(q, [0.0]*6, [0.0]*6, asset.JOINT_LIMITS, 1.0, None)
        self.assertEqual(caught.exception.category, "state_invalid")


class HoldDiagnosticsTests(unittest.TestCase):
    """New holding diagnostics only; no asset fixture or generation is used."""

    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory(prefix="cr12_hold_cpu_")
        self.addCleanup(self.temporary.cleanup)

    def trace(self, name="joint_trace.csv"):
        trace = hold.JointTrace(Path(self.temporary.name) / name)
        self.addCleanup(trace.close)
        return trace

    @staticmethod
    def sample(trace, step, speed=None):
        time = step/120
        reference, velocity = asset.trajectory(time)
        trace.append(step, .0166666675+time, time, time, reference.astype(np.float32),
                     velocity.astype(np.float32), reference, velocity if speed is None else speed,
                     q_reference=reference)

    @staticmethod
    def pass_checks(trace, step):
        for name in hold.CHECK_NAMES:
            trace.mark_check(name, step=step)

    def test_no_samples_and_close_do_not_report_zero_or_success(self):
        trace = self.trace()
        trace.close()
        result = trace.summary()
        window = result["windows"]["strict_hold"]
        self.assertEqual(window["sample_count"], 0)
        self.assertIsNone(window["max_abs_error_rad"])
        self.assertIsNone(window["max_abs_speed_rad_s"])
        self.assertIsNone(window["start_step"])
        self.assertFalse(window["complete"])
        self.assertFalse(result["baseline"]["observed"])
        self.assertNotIn("success", result)
        self.assertFalse(result["coverage"]["joint"]["complete"])

    def test_first_strict_hold_failure_is_retained_with_real_maximum(self):
        trace = self.trace()
        for step in range(600):
            self.sample(trace, step)
            self.pass_checks(trace, step)
        speed = [0.0]*6
        speed[4], speed[5] = -.023184916, -.025973620
        self.sample(trace, 600, speed)
        trace.mark_check("clock")
        trace.mark_check("contact")
        q, _ = asset.trajectory(5)
        with self.assertRaises(drive.DriveCheckError):
            drive.check_joint_sample(q, speed, q, asset.JOINT_LIMITS, 5, 0.0)
        trace.mark_check("joint", "FAIL", details="strict hold velocity")
        trace.flush()
        result = trace.summary()
        window = result["windows"]["strict_hold"]
        self.assertEqual((window["sample_count"], window["expected_sample_count"]), (1, 121))
        self.assertEqual((window["start_step"], window["end_step"]), (600, 600))
        self.assertEqual(window["max_abs_speed_rad_s"][5], .025973620)
        self.assertFalse(window["complete"])
        self.assertTrue(result["has_failure"])
        self.assertEqual(result["coverage"]["geometry"]["last_step"], 599)
        self.assertEqual(result["coverage"]["joint"]["failed_sample_count"], 1)
        with trace.path.open(newline="", encoding="utf-8") as stream:
            rows = list(csv.DictReader(stream))
        self.assertEqual(len(rows), 601)
        self.assertEqual(rows[-1]["step"], "600")
        self.assertEqual(rows[-1]["check_geometry"], "NOT_CHECKED")
        self.assertEqual(rows[-1]["check_frame"], "NOT_CHECKED")
        self.assertEqual(float(rows[-1]["dq_6_rad_s"]), -.025973620)

    def test_earlier_contact_failure_has_no_invented_state_sample(self):
        trace = self.trace()
        self.sample(trace, 0)
        trace.mark_check("clock", "PASS", step=1)
        trace.mark_check("contact", "ERROR", step=1, details="unreadable filter data")
        trace.flush()
        result = trace.summary()
        self.assertEqual(result["windows"]["all_controlled"]["sample_count"], 0)
        self.assertEqual(result["coverage"]["contact"]["attempted_sample_count"], 1)
        self.assertEqual(result["coverage"]["contact"]["checked_sample_count"], 0)
        self.assertEqual(result["coverage"]["geometry"]["attempted_sample_count"], 0)
        self.assertIsNone(result["coverage"]["contact"]["end_actual_time_s"])
        self.assertTrue(result["has_failure"])

    def test_snapshots_and_math_reference_are_independent_copies(self):
        trace = self.trace()
        self.sample(trace, 0)
        command = np.full(6, .1, dtype=np.float32)
        actual = np.full(6, .099, dtype=np.float64)
        velocity = np.zeros(6)
        reference = np.full(6, .1, dtype=np.float64)
        trace.append(1, 1., 1/120, 1/120, command, velocity, actual, velocity, q_reference=reference)
        command[:], actual[:], velocity[:], reference[:] = 99, 99, 99, 99
        trace.flush()
        result = trace.summary()
        np.testing.assert_allclose(result["windows"]["all_controlled"]["max_abs_error_rad"], [.001]*6, atol=1e-16, rtol=0)
        self.assertEqual(result["math_reference_sample_count"], 1)
        with trace.path.open(newline="", encoding="utf-8") as stream:
            row = list(csv.DictReader(stream))[-1]
        self.assertEqual(float(row["q_target_1_rad"]), float(np.float32(.1)))
        self.assertEqual(float(row["q_1_rad"]), .099)
        self.assertEqual(float(row["dq_1_rad_s"]), 0)

    def test_complete_boundaries_and_strict_window_have_121_samples(self):
        trace = self.trace()
        for step in range(721):
            self.sample(trace, step)
            self.pass_checks(trace, step)
            if step in (120, 240, 360, 600, 720):
                trace.flush()
        trace.close()
        result = trace.summary()
        self.assertEqual(result["windows"]["all_controlled"]["sample_count"], 720)
        self.assertEqual(result["math_reference_sample_count"], 720)
        strict = result["windows"]["strict_hold"]
        self.assertEqual((strict["sample_count"], strict["start_step"], strict["end_step"]), (121, 600, 720))
        self.assertEqual((strict["start_reference_time_s"], strict["end_reference_time_s"]), (5., 6.))
        self.assertTrue(strict["complete"])
        self.assertTrue(all(value["complete"] and value["passed_sample_count"] == 720 for value in result["coverage"].values()))
        self.assertFalse(result["has_failure"])
        self.assertEqual(result["invalid_sample_count"], 0)
        with trace.path.open(newline="", encoding="utf-8") as stream:
            rows = list(csv.DictReader(stream))
        self.assertEqual(len(rows), 721)
        self.assertEqual([rows[s]["phase"] for s in (120, 240, 360, 600, 720)],
                         ["initial_hold", "motion", "motion", "strict_hold", "strict_hold"])
        self.assertEqual(float(rows[240]["reference_time_s"]), 2)
        self.assertAlmostEqual(float(rows[240]["q_target_2_rad"]), math.radians(2.5), places=8)
        self.assertEqual(float(rows[360]["dq_target_2_rad_s"]), 0)
        # Exercise the real driver's summary consumer and exact final condition,
        # without invoking its runtime-containing _run_drive function.
        recorder = drive.Recorder()
        recorder.result["drive_summary"] = {}
        drive._sync_diagnostics(recorder, trace)
        source = ast.parse((REPO_ROOT / "scripts/environments/run_cr12_joint_drive.py").read_text(encoding="utf-8"))
        run_function = next(node for node in source.body if isinstance(node, ast.FunctionDef) and node.name == "_run_drive")
        condition = next(node.value for node in ast.walk(run_function)
                         if isinstance(node, ast.Assign) and any("diagnostics_complete" in ast.unparse(target) for target in node.targets))
        compiled = compile(ast.Expression(condition), "driver_diagnostic_success_condition", "eval")
        self.assertTrue(eval(compiled, {"diagnostic_summary": recorder.result["joint_diagnostics_summary"]}))
        failed = json.loads(json.dumps(result))
        failed["recording_error"] = "write failed"
        self.assertFalse(eval(compiled, {"diagnostic_summary": failed}))

    def test_nonfinite_sample_is_saved_and_never_promoted_to_valid(self):
        trace = self.trace()
        self.sample(trace, 0)
        values = [0.0]*6
        invalid = [float("nan")]+values[1:]
        trace.append(1, .025, 1/120, 1/120, values, values, invalid, values, q_reference=values)
        trace.flush()
        result = trace.summary()
        window = result["windows"]["all_controlled"]
        self.assertEqual((window["sample_count"], window["finite_sample_count"]), (1, 0))
        self.assertIsNone(window["max_abs_error_rad"])
        self.assertTrue(result["has_failure"])
        self.assertEqual(result["invalid_sample_count"], 1)
        json.dumps(result, allow_nan=False)
        with trace.path.open(newline="", encoding="utf-8") as stream:
            row = list(csv.DictReader(stream))[-1]
        self.assertEqual(row["q_1_rad"], "nan")
        self.assertEqual(row["sample_valid"], "False")

    def test_recording_error_and_late_failure_preserve_failure(self):
        trace = self.trace()
        self.sample(trace, 0)
        trace.flush()
        before = trace.path.read_bytes()
        trace.mark_failure("render", "failure after stage flush", step=0)
        self.assertEqual(trace.path.read_bytes(), before)
        self.assertTrue(trace.summary()["failures"][-1]["row_already_written"])
        self.sample(trace, 1)
        with mock.patch.object(trace, "_writer") as writer:
            writer.writerow.side_effect = OSError("disk full")
            with self.assertRaisesRegex(OSError, "disk full"):
                trace.flush()
        result = trace.summary()
        self.assertTrue(result["has_failure"])
        self.assertIn("disk full", result["recording_error"])
        trace.close()
        self.assertTrue(trace.summary()["has_failure"])

    def test_previous_row_write_failure_keeps_current_acquired_sample(self):
        trace = self.trace()
        self.sample(trace, 0)
        with mock.patch.object(trace, "_writer") as writer:
            writer.writerow.side_effect = OSError("prior-row write failed")
            with self.assertRaisesRegex(OSError, "prior-row"):
                self.sample(trace, 1)
        summary = trace.summary()
        self.assertEqual(summary["windows"]["all_controlled"]["sample_count"], 1)
        self.assertEqual(summary["windows"]["all_controlled"]["end_step"], 1)
        self.assertTrue(summary["has_failure"])
        self.assertIn("prior-row", summary["recording_error"])

    def test_pd_baseline_bounds_limits_and_unknown_candidate(self):
        baseline = hold.select_pd_profile("baseline")
        self.assertEqual(baseline["stiffness"], [200, 4000, 2000, 200, 1000, 150])
        baseline["stiffness"][4] = -10
        self.assertEqual(hold.select_pd_profile("baseline")["stiffness"][4], 1000)
        with self.assertRaises(ValueError):
            hold.select_pd_profile("undefined_profile")
        candidate = hold.select_pd_profile("baseline")
        candidate["name"] = "test_only_not_registered"
        candidate["damping"][4] = 2*math.sqrt(candidate["stiffness"][4]*candidate["J"][4])
        self.assertEqual(hold.validate_pd_profile(candidate)["changed_joints"], ["joint_5"])
        for field, index, value in (("stiffness", 4, 1250.01), ("damping", 4, 500), ("effort_limits", 4, 11)):
            changed = json.loads(json.dumps(candidate))
            changed[field][index] = value
            with self.assertRaises(ValueError):
                hold.validate_pd_profile(changed)
        parser = argparse.ArgumentParser()
        hold.add_diagnostic_arguments(parser)
        args = parser.parse_args(["--record-joint-trace", "--pd-profile", "baseline"])
        self.assertTrue(args.record_joint_trace)
        self.assertEqual(args.pd_profile, "baseline")
        with mock.patch("sys.stderr", new=io.StringIO()), self.assertRaises(SystemExit):
            parser.parse_args(["--pd-profile", "undefined"])

    def test_hold_tune_01_changes_only_two_damping_values_at_exact_upper_bound(self):
        baseline = hold.select_pd_profile("baseline")
        candidate = hold.select_pd_profile("hold_tune_01")
        self.assertEqual(baseline["damping"], [20, 550, 166, 12, 37, 7])
        self.assertEqual(candidate["changed_joints"], ["joint_5", "joint_6"])
        for field in ("stiffness", "effort_limits", "velocity_limit", "J"):
            self.assertEqual(candidate[field], baseline[field])
        self.assertEqual(candidate["damping"][:4], baseline["damping"][:4])
        self.assertEqual(candidate["damping"][4:], [44.03609933679412, 8.48098097910849])
        for index in (4, 5):
            upper = 1.2*(2*math.sqrt(candidate["stiffness"][index]*candidate["J"][index]))
            self.assertEqual(candidate["damping"][index], upper)
            exceeded = json.loads(json.dumps(candidate))
            exceeded["damping"][index] = math.nextafter(upper, math.inf)
            with self.assertRaisesRegex(ValueError, "damping exceeds"):
                hold.validate_pd_profile(exceeded)
        parser = argparse.ArgumentParser()
        hold.add_diagnostic_arguments(parser)
        self.assertEqual(parser.parse_args(["--pd-profile", "hold_tune_01"]).pd_profile, "hold_tune_01")
        candidate["damping"][4] = -10
        self.assertEqual(hold.select_pd_profile("hold_tune_01")["damping"][4], 44.03609933679412)
        self.assertEqual(hold.select_pd_profile("baseline")["damping"], [20, 550, 166, 12, 37, 7])

    def test_hold_tune_02_changes_only_two_axes_at_original_baseline_bounds(self):
        baseline = hold.select_pd_profile("baseline")
        previous = hold.select_pd_profile("hold_tune_01")
        candidate = hold.select_pd_profile("hold_tune_02")
        self.assertEqual(candidate["stiffness"], [200, 4000, 2000, 200, 1250, 187.5])
        self.assertEqual(candidate["damping"], [20, 550, 166, 12, 49.23385579050253, 9.482024992584654])
        self.assertEqual(candidate["changed_joints"], ["joint_5", "joint_6"])
        for field in ("effort_limits", "velocity_limit", "J"):
            self.assertEqual(candidate[field], baseline[field])
        for index in (4, 5):
            k_upper = 1.25*baseline["stiffness"][index]
            d_upper = 1.2*(2*math.sqrt(k_upper*baseline["J"][index]))
            self.assertEqual(candidate["stiffness"][index], k_upper)
            self.assertEqual(candidate["damping"][index], d_upper)
            for field, upper in (("stiffness", k_upper), ("damping", d_upper)):
                exceeded = json.loads(json.dumps(candidate))
                exceeded[field][index] = math.nextafter(upper, math.inf)
                with self.assertRaisesRegex(ValueError, f"{field} exceeds"):
                    hold.validate_pd_profile(exceeded)
        parser = argparse.ArgumentParser()
        hold.add_diagnostic_arguments(parser)
        self.assertEqual(parser.parse_args(["--pd-profile", "hold_tune_02"]).pd_profile, "hold_tune_02")
        candidate["stiffness"][4] = -10
        candidate["damping"][5] = -10
        self.assertEqual(hold.select_pd_profile("hold_tune_02")["stiffness"][4], 1250)
        self.assertEqual(hold.select_pd_profile("hold_tune_02")["damping"][5], 9.482024992584654)
        self.assertEqual(hold.select_pd_profile("baseline"), baseline)
        self.assertEqual(hold.select_pd_profile("hold_tune_01"), previous)

    def test_actual_driver_parser_and_primary_exception_preservation(self):
        class FakeLauncher:
            @staticmethod
            def add_app_launcher_args(parser):
                parser.add_argument("--device", default="cuda:0")
                parser.add_argument("--headless", action="store_true")
                parser.add_argument("--enable_cameras", action="store_true")
                parser.add_argument("--livestream", type=int, default=-1)
                parser.add_argument("--xr", action="store_true")
        path = Path(self.temporary.name) / "parser_fixture.usd"
        path.write_text("parser fixture only", encoding="utf-8")
        argv = ["run_cr12_joint_drive.py", "--usd-path", str(path), "--output-dir", self.temporary.name,
                "--record-joint-trace", "--pd-profile", "baseline"]
        with mock.patch.dict(sys.modules, {"_cr12_hold_diagnostics": hold}), mock.patch.dict(os.environ, {}, clear=True), mock.patch.object(sys, "argv", argv):
            args = drive._parse_args(FakeLauncher)
            self.assertTrue(args.record_joint_trace)
            self.assertEqual(args.pd_profile, "baseline")
            self.assertEqual(args.usd_path, path.resolve())
        recorder = drive.Recorder()
        primary = drive.DriveCheckError("tracking", "primary strict-hold failure")
        with mock.patch.object(recorder, "emit", side_effect=OSError("console broken")), mock.patch.object(recorder, "save", side_effect=OSError("result disk full")), mock.patch("sys.stderr", new=io.StringIO()):
            recorder.fail(primary)
        self.assertEqual(recorder.result["status"], "FAILED")
        self.assertEqual(recorder.result["failures"][0]["message"], "primary strict-hold failure")
        self.assertEqual(len(recorder.result["secondary_failures"]), 2)
        self.assertFalse(recorder.result["diagnostics_complete"])
        self.assertFalse(recorder.result["work_completed"])
        self.assertFalse(any(name == "torch" or name == "pxr" or name.startswith(("isaaclab", "isaacsim", "omni.")) for name in sys.modules))


if __name__ == "__main__":
    unittest.main(verbosity=2)
