"""CPU-only preparation and checks for the approved CR12 fixed-lift asset.

The source mass values are unverified inputs, not manufacturer identification.
No simulator, tensor runtime, or USD package is imported here.  The only writer
uses exclusive creation of a new derived URDF; source assets are read-only.
"""

from __future__ import annotations

import copy
import hashlib
import json
import math
from pathlib import Path
import xml.etree.ElementTree as ET

import numpy as np


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SOURCE_URDF = REPO_ROOT / "source/isaaclab_tasks/isaaclab_tasks/direct/scan_mobile_manipulator/assets/rokeaCR12/rokea_cr12_7DOF.urdf"
ASSET_VERSION = "cr12_fixed_lift0_visual_box_v1"
BODY_NAMES = ("agv", "link_1", "link_2", "link_3", "link_4", "link_5", "link_6")
JOINT_NAMES = tuple(f"joint_{i}" for i in range(1, 7))
JOINT_LIMITS = ((-3.0543, 3.0543), (-2.9671, 2.9671)) + ((-3.0543, 3.0543),) * 4
ROOT_TRANSLATION = (0.0, 0.0, 0.053)
DT = 1.0 / 120.0
PHYSICS_STEPS = 720
TOTAL_MASS = 82.860365324
SOURCE_MASSES = {
    "agv": 50.0, "elevate": 10.0, "base_link": 3.44074938,
    "link_1": 3.44074938, "link_2": 5.024380503, "link_3": 2.439584706,
    "link_4": 2.439584706, "link_5": 2.422757896, "link_6": 1.229800857,
    "scanner": 2.422757896,
}

# Independent constants from the reviewed CPU calculation, not generated by the
# implementation below.  Six tensor components are about the specified COM.
_APPROVED_VALUES = {
    "agv": (63.44074938, (.009847509526981598, .0006037831298602024, .6100607573843),
            (11.110953937031162, -.0024589072476622568, -.19641828154607133,
             12.797724005574134, -.019800414112534564, 8.17358518695085)),
    "link_1": (3.44074938, (-.000008324, .003624203, .283859081),
               (.0407314029409739, 0, 0, .04000239495867654, 0, .022845592193449473)),
    "link_2": (5.024380503, (-.000023014, .191745411, .369056328),
               (.37951624430139336, 0, 0, .3797735206603749, 0, .028452046612631277)),
    "link_3": (2.439584706, (-.000072464, .0215122375, .064993309),
               (.021837733469756444, 0, 0, .02086571367366181, 0, .010365226827775118)),
    "link_4": (2.439584706, (.000037994, -.009180899, -.141903635),
               (.03552070676427747, 0, 0, .03432331714264283, 0, .006663129056876105)),
    "link_5": (2.422757896, (-.000008404, .011287979, -.0245845105),
               (.011912174503244553, 0, 0, .01102473334143262, 0, .005939185186319027)),
    "link_6": (3.652558753, (.06071267344171582, .06071821788515036, .11853282647734235),
               (.09761583941767576, -.00912286701490933, -.016382306980800274,
                .09762701393460375, -.01636653580809325, .056319554644805946)),
}

APPROVED_SOURCE_HASHES = {"rokea_cr12_7DOF.urdf": "f7830ca8b0974c9c27e2cfda4b0d966674c0cf64a3bb21cfe0ebb9f98ec04c43"}
for _prefix, _digest in {
    "cr12_base": "54e4123538b3eb3c644982699246ef320c601f60efaa5cb4ef2dd7e621a024ef",
    "cr12_link1": "153dc9eb5162bd2e44ddc5baef213bf67f1ddb0e9f70cc6289ab05a991ab315e",
    "cr12_link2": "8402fba4c997e1bf9b5fe7fea5cb50af0fb9e7c28f5465ac08a41cbd3fafab97",
    "cr12_link3": "dc6e0f88f42a6057c5747d6feacf0a545c4ce306dd90c94eaefaa5ac6a9bc5a3",
    "cr12_link4": "892cd70cabe776e7aa44a230d218931cbcb04ab83020cdd897cc52d6130973cd",
    "cr12_link5": "5de570d93e5eee95be64ac631dd92ca5fd5b2129e1543246a10741421494925e",
    "cr12_link6": "38a65bceaaf12c481a7a1f0256102a08152064bc4e4046f4760344086e711739",
}.items():
    for _kind in ("visual", "collision"):
        APPROVED_SOURCE_HASHES[f"model/{_prefix}_{_kind}.obj"] = _digest
APPROVED_SOURCE_HASHES.update({
    "model/scanner_sys_agv_collision.obj": "0251c90f59d418237d0a11edd55c2ec976970c37275fa9e37fa2337177e2f760",
    "model/scanner_sys_agv_visual.obj": "3eafc4d54bb47b44cee5d42b7d3857e1812e4bad2cf8dbc1f75d745974cdca7a",
    "model/scanner_sys_elevate_collision.obj": "e965fe59951cf626d14a58c8c0fef18c8bc5ffb06a18f8ba3d82df9ef78843bb",
    "model/scanner_sys_elevate_visual.obj": "23ef9954f92eb4dfb88109f6c1ff22dfce68a096484c42329c45d14d7d27084d",
    "model/scanner_sys_scanner_collision.obj": "5d1126ea11da5a84150c375711b8cb8c98cdd513ff8248c8e3c790bb0db5a9ab",
    "model/scanner_sys_scanner_visual.obj": "284e925e0fb874bc98104b9f439c44bccb0e2850fe3dba7380b54d91dc5e9db5",
})


def _array(values, shape):
    result = np.asarray(values, dtype=np.float64)
    if result.shape != shape or not np.isfinite(result).all():
        raise ValueError(f"Expected finite array of shape {shape}, got {result.shape}")
    return result


def inertia_matrix(six):
    """Convert URDF Ixx,Ixy,Ixz,Iyy,Iyz,Izz to a symmetric float64 matrix."""
    xx, xy, xz, yy, yz, zz = _array(six, (6,))
    return np.array(((xx, xy, xz), (xy, yy, yz), (xz, yz, zz)), dtype=np.float64)


def _properties(mass, com, inertia):
    matrix = _array(inertia, (3, 3)).tolist()
    return {"mass": float(mass), "com": _array(com, (3,)).tolist(),
            "inertia3x3": matrix, "inertia": copy.deepcopy(matrix)}


APPROVED_BODIES = {name: _properties(mass, com, inertia_matrix(six))
                   for name, (mass, com, six) in _APPROVED_VALUES.items()}


def rpy_matrix(rpy):
    """URDF fixed-axis roll/pitch/yaw, Rz(yaw) Ry(pitch) Rx(roll)."""
    r, p, y = _array(rpy, (3,))
    cr, sr, cp, sp, cy, sy = math.cos(r), math.sin(r), math.cos(p), math.sin(p), math.cos(y), math.sin(y)
    return np.array(((cy*cp, cy*sp*sr-sy*cr, cy*sp*cr+sy*sr),
                     (sy*cp, sy*sp*sr+cy*cr, sy*sp*cr-cy*sr), (-sp, cp*sr, cp*cr)))


def quaternion_matrix(quaternion, order="wxyz"):
    """Rotation only; callers must explicitly choose the native quaternion order."""
    q = _array(quaternion, (4,))
    if order == "xyzw":
        q = q[[3, 0, 1, 2]]
    elif order != "wxyz":
        raise ValueError("Quaternion order must be wxyz or xyzw")
    norm = np.linalg.norm(q)
    if not np.isclose(norm, 1, atol=1e-5, rtol=0):
        raise ValueError("Quaternion is not unit length")
    w, x, y, z = q / norm
    return np.array(((1-2*(y*y+z*z), 2*(x*y-z*w), 2*(x*z+y*w)),
                     (2*(x*y+z*w), 1-2*(x*x+z*z), 2*(y*z-x*w)),
                     (2*(x*z-y*w), 2*(y*z+x*w), 1-2*(x*x+y*y))))


def name_indices(actual_names, expected_names):
    """Map approved order to a native array; reject duplicates/missing/extra names."""
    actual, expected = tuple(actual_names), tuple(expected_names)
    if len(set(actual)) != len(actual) or len(set(expected)) != len(expected) or set(actual) != set(expected):
        raise ValueError(f"Name set mismatch: actual={actual}, expected={expected}")
    return [actual.index(name) for name in expected]


def checked_physx_body_inertia(raw_tensor, com_quaternion_xyzw, usd_diagonal):
    """Read the local 4.5 tensor API's full inertia about COM in object axes.

    The nine values already include the principal-axis rotation. The local
    RigidBodyView documentation explicitly says object frame; ArticulationView's
    shorter 'COM local frame' phrase must not cause another rotation. Check the
    observed COM principal axes against independently read USD diagonal values;
    never choose a transform based on which result fits expected body inertia.
    """
    tensor = _array(raw_tensor, (3, 3))
    rotation = quaternion_matrix(com_quaternion_xyzw, order="xyzw")
    diagonal = _array(usd_diagonal, (3,))
    if not np.allclose(rotation.T @ tensor @ rotation, np.diag(diagonal), atol=1e-6, rtol=1e-4):
        raise ValueError("PhysX object-axis inertia and COM principal axes disagree with USD diagonal inertia")
    return tensor.copy()


def trajectory(t):
    """Approved six-axis position/velocity at an explicit simulation time in [0,6]."""
    if not math.isfinite(t) or t < 0 or t > 6.0 + 1e-10:
        raise ValueError("Controlled trajectory time must be in [0, 6] seconds")
    q, dq = np.zeros(6, dtype=np.float64), np.zeros(6, dtype=np.float64)
    s = min(1.0, max(0.0, (float(t)-1.0)/2.0))
    q[1] = math.radians(5) * (10*s**3 - 15*s**4 + 6*s**5)
    dq[1] = math.radians(5) * (30*s**2 - 60*s**3 + 30*s**4) / 2
    return q, dq


def step_reference_times(step_index, dt=DT):
    """Zero-based controlled step: submitted time, then measured state time."""
    if isinstance(step_index, bool) or not isinstance(step_index, (int, np.integer)) or not 0 <= step_index < PHYSICS_STEPS:
        raise ValueError("Controlled step index must be an integer in [0,719]")
    if not math.isclose(dt, DT, rel_tol=0, abs_tol=1e-15):
        raise ValueError("The approved physics timestep is 1/120 s")
    return step_index * DT, (step_index + 1) * DT


def source_fingerprint(source=DEFAULT_SOURCE_URDF):
    """Hash exactly the source URDF and its 20 approved mesh inputs."""
    source = Path(source).resolve(strict=True)
    hashes = {}
    for key, expected in APPROVED_SOURCE_HASHES.items():
        path = source if key == "rokea_cr12_7DOF.urdf" else source.parent / key
        actual = hashlib.sha256(path.read_bytes()).hexdigest()
        if actual != expected:
            raise ValueError(f"Approved source changed: {path}; expected {expected}, got {actual}")
        hashes[key] = actual
    signature = hashlib.sha256(json.dumps(hashes, sort_keys=True, separators=(",", ":")).encode("ascii")).hexdigest()
    return {"source_path": str(source), "source_hashes": hashes, "source_signature": signature}


def inertia_checks(inertia):
    matrix = _array(inertia, (3, 3))
    if not np.allclose(matrix, matrix.T, atol=1e-14, rtol=0):
        raise ValueError("Inertia tensor is not symmetric")
    eigenvalues = np.linalg.eigvalsh(matrix)
    margin = float(eigenvalues[0] + eigenvalues[1] - eigenvalues[2])
    return {"eigenvalues": eigenvalues.tolist(), "triangle_margin": margin,
            "positive_definite": bool(eigenvalues[0] > 0), "triangle_valid": margin >= -1e-12}


def box_properties(mass, bounds_min, bounds_max):
    lo, hi = _array(bounds_min, (3,)), _array(bounds_max, (3,))
    d = hi - lo
    if not math.isfinite(mass) or mass <= 0 or np.any(d <= 0):
        raise ValueError("Box mass and all dimensions must be positive")
    inertia = np.diag(mass/12 * np.array((d[1]**2+d[2]**2, d[0]**2+d[2]**2, d[0]**2+d[1]**2)))
    return _properties(mass, (lo+hi)/2, inertia)


def merge_properties(components):
    """Merge (properties, rotation, translation), always about the combined COM."""
    transformed = []
    for body, rotation, translation in components:
        R, t = _array(rotation, (3, 3)), _array(translation, (3,))
        if not np.allclose(R.T@R, np.eye(3), atol=1e-12) or not np.isclose(np.linalg.det(R), 1):
            raise ValueError("Invalid rigid rotation")
        transformed.append((body["mass"], R@np.asarray(body["com"])+t, R@np.asarray(body["inertia3x3"])@R.T))
    if not transformed or any(not math.isfinite(m) or m <= 0 for m, _, _ in transformed):
        raise ValueError("Merged components require positive masses")
    mass = sum(item[0] for item in transformed)
    com = sum(m*c for m, c, _ in transformed)/mass
    inertia = np.zeros((3, 3))
    for m, c, tensor in transformed:
        d = c-com
        inertia += tensor + m*((d@d)*np.eye(3)-np.outer(d, d))
    return _properties(mass, com, inertia)


def _vector(element, attribute, default="0 0 0"):
    return _array([float(x) for x in element.get(attribute, default).split()], (3,))


def _origin(element):
    origin = element.find("origin")
    return (np.zeros(3), np.zeros(3)) if origin is None else (_vector(origin, "xyz"), _vector(origin, "rpy"))


def _vertices(path):
    values = []
    with path.open(encoding="utf-8") as stream:
        for line in stream:
            fields = line.split()
            if fields and fields[0] == "v":
                if len(fields) not in (4, 5) or (len(fields) == 5 and float(fields[4]) != 1):
                    raise ValueError(f"Unsupported OBJ vertex: {path}")
                values.append([float(x) for x in fields[1:4]])
    vertices = np.asarray(values, dtype=np.float64)
    if vertices.ndim != 2 or vertices.shape[1] != 3 or not np.isfinite(vertices).all():
        raise ValueError(f"Invalid/empty OBJ vertices: {path}")
    return vertices


def geometry_body_bounds(geometry):
    """Exact vertex AABB in body axes for an already source-validated geometry.

    Apply the mesh scale once, then its body-local origin. Rotating the eight
    original AABB corners would give a different, more conservative bound.
    """
    vertices = _vertices(Path(geometry["filename"]).resolve(strict=True))
    vertices = vertices * _array(geometry["scale"], (3,))
    vertices = vertices @ rpy_matrix(geometry["origin_rpy"]).T + _array(geometry["origin_xyz"], (3,))
    return vertices.min(axis=0), vertices.max(axis=0)


def _group_transform(name):
    if name == "elevate":
        return "agv", np.array((0., 0., .314)), np.zeros(3)
    if name == "base_link":
        return "agv", np.array((.105, 0., 1.062)), np.zeros(3)
    if name == "scanner":
        return "link_6", np.zeros(3), np.array((0., 0., 2.356194490192345))
    return name, np.zeros(3), np.zeros(3)


def _compare_body(name, observed, expected, atol=2e-11):
    if not math.isclose(observed["mass"], expected["mass"], rel_tol=0, abs_tol=atol):
        raise ValueError(f"{name}: mass differs from approved value")
    for key in ("com", "inertia3x3"):
        if not np.allclose(observed[key], expected[key], atol=atol, rtol=1e-12):
            raise ValueError(f"{name}: {key} differs from approved value")
    checks = inertia_checks(observed["inertia3x3"])
    if not checks["positive_definite"] or not checks["triangle_valid"]:
        raise ValueError(f"{name}: invalid physical inertia")


def analyze_source(source_urdf=DEFAULT_SOURCE_URDF):
    """Compute the approved model from immutable inputs, checked against constants."""
    source = Path(source_urdf).resolve(strict=True)
    summary = source_fingerprint(source)
    root = ET.parse(source).getroot()
    links = {node.attrib["name"]: node for node in root.findall("link")}
    if len(links) != 12 or set(links) != set(SOURCE_MASSES) | {"world", "tool"}:
        raise ValueError("Unexpected original link set")
    candidates, original, geometries = {}, {}, {name: [] for name in BODY_NAMES}
    components = {name: [] for name in BODY_NAMES}
    for name, mass in SOURCE_MASSES.items():
        link = links[name]
        inertial = link.find("inertial")
        if float(inertial.find("mass").get("value")) != mass:
            raise ValueError(f"{name}: original mass changed")
        attr = inertial.find("inertia").attrib
        tensor = inertia_matrix([float(attr[key]) for key in ("ixx", "ixy", "ixz", "iyy", "iyz", "izz")])
        com, inertial_rpy = _origin(inertial)
        if np.any(inertial_rpy):
            raise ValueError("Source inertial rotation changed")
        original[name] = {**_properties(mass, com, tensor), **inertia_checks(tensor)}
        group, group_t, group_rpy = _group_transform(name)
        for kind in ("visual", "collision"):
            nodes = link.findall(kind)
            if len(nodes) != 1:
                raise ValueError(f"{name}: expected one {kind}")
            node = nodes[0]
            t, rpy = _origin(node)
            if np.any(t) or np.any(rpy):
                raise ValueError("Original geometry origin changed")
            mesh = node.find("geometry/mesh")
            path = Path(mesh.get("filename")).resolve(strict=True)
            expected_path = (source.parent / "model" / path.name).resolve(strict=True)
            if path != expected_path:
                raise ValueError(f"Original mesh is outside approved model directory: {path}")
            scale = _vector(mesh, "scale", "1 1 1")
            if not np.array_equal(scale, np.full(3, .001)):
                raise ValueError("Source mesh scale changed")
            vertices = _vertices(path)*scale
            lo, hi = vertices.min(axis=0), vertices.max(axis=0)
            geometries[group].append({"name": f"{name}_{kind}", "source_link": name, "kind": kind,
                                      "filename": str(path), "scale": scale.tolist(),
                                      "origin_xyz": group_t.tolist(), "origin_rpy": group_rpy.tolist(),
                                      "bounds_min": lo.tolist(), "bounds_max": hi.tolist()})
            if kind == "visual":
                candidates[name] = {**box_properties(mass, lo, hi), "size": (hi-lo).tolist(),
                                    "bounds_min": lo.tolist(), "bounds_max": hi.tolist()}
        components[group].append((candidates[name], rpy_matrix(group_rpy), group_t))
    bodies = {name: merge_properties(components[name]) for name in BODY_NAMES}
    for name in BODY_NAMES:
        _compare_body(name, bodies[name], APPROVED_BODIES[name])
    if not math.isclose(sum(body["mass"] for body in bodies.values()), TOTAL_MASS, abs_tol=1e-11, rel_tol=0):
        raise ValueError("Total mass differs from approved model")
    joints = []
    for index, name in enumerate(JOINT_NAMES):
        joint = root.find(f"joint[@name='{name}']")
        t, rpy = _origin(joint)
        if index == 0:
            t = np.array((.105, 0., 1.062))
        limits = joint.find("limit")
        joints.append({"name": name, "type": "revolute", "parent": BODY_NAMES[index],
                       "child": BODY_NAMES[index+1], "origin_xyz": t.tolist(), "origin_rpy": rpy.tolist(),
                       "axis": _vector(joint.find("axis"), "xyz").tolist(),
                       "lower": float(limits.get("lower")), "upper": float(limits.get("upper")),
                       "velocity": float(limits.get("velocity")), "effort": float(limits.get("effort")),
                       "damping": float(joint.find("dynamics").get("damping"))})
    summary.update({"asset_version": ASSET_VERSION, "bodies": bodies, "candidates": candidates,
                    "original": original, "geometries": geometries, "joints": joints,
                    "total_mass": TOTAL_MASS, "root_translation": list(ROOT_TRANSLATION)})
    return summary


def _numbers(values):
    return " ".join(format(float(v), ".17g") for v in values)


def _make_tree(source, summary):
    source_root = ET.parse(source).getroot()
    root = ET.Element("robot", {"name": ASSET_VERSION})
    for name in BODY_NAMES:
        link = ET.SubElement(root, "link", {"name": name})
        for geometry in summary["geometries"][name]:
            original = source_root.find(f"link[@name='{geometry['source_link']}']/{geometry['kind']}")
            node = copy.deepcopy(original)
            node.set("name", geometry["name"])
            origin = node.find("origin")
            origin.set("xyz", _numbers(geometry["origin_xyz"]))
            origin.set("rpy", _numbers(geometry["origin_rpy"]))
            node.find("geometry/mesh").set("filename", f"../../model/{Path(geometry['filename']).name}")
            link.append(node)
        body = summary["bodies"][name]
        inertial = ET.SubElement(link, "inertial")
        ET.SubElement(inertial, "mass", {"value": format(body["mass"], ".17g")})
        ET.SubElement(inertial, "origin", {"xyz": _numbers(body["com"]), "rpy": "0 0 0"})
        I = np.asarray(body["inertia3x3"])
        ET.SubElement(inertial, "inertia", dict(zip(("ixx", "ixy", "ixz", "iyy", "iyz", "izz"),
                      (format(float(v), ".17g") for v in (I[0,0], I[0,1], I[0,2], I[1,1], I[1,2], I[2,2])))))
    for name in JOINT_NAMES:
        joint = copy.deepcopy(source_root.find(f"joint[@name='{name}']"))
        if name == "joint_1":
            joint.find("parent").set("link", "agv")
            joint.find("origin").set("xyz", _numbers((.105, 0, 1.062)))
        root.append(joint)
    return root


def _validate_tree(root, path, source, expected):
    links, joints = root.findall("link"), root.findall("joint")
    name_indices([node.get("name") for node in links], BODY_NAMES)
    name_indices([node.get("name") for node in joints], JOINT_NAMES)
    if root.get("name") != ASSET_VERSION or len(root) != 13:
        raise ValueError("Unexpected derived robot structure/version")
    observed_bodies = {}
    for link in links:
        name = link.get("name")
        if len(link.findall("inertial")) != 1:
            raise ValueError(f"{name}: expected exactly one inertial")
        inertial = link.find("inertial")
        if [child.tag for child in inertial] != ["mass", "origin", "inertia"]:
            raise ValueError(f"{name}: ambiguous or extra inertial fields")
        com, rpy = _origin(inertial)
        if np.any(rpy):
            raise ValueError("Derived inertial axes must match body axes")
        attr = inertial.find("inertia").attrib
        observed = _properties(float(inertial.find("mass").get("value")), com,
                               inertia_matrix([float(attr[key]) for key in ("ixx", "ixy", "ixz", "iyy", "iyz", "izz")]))
        _compare_body(name, observed, APPROVED_BODIES[name])
        observed_bodies[name] = observed
        observed_geometries = link.findall("visual") + link.findall("collision")
        required = {geometry["name"]: geometry for geometry in expected["geometries"][name]}
        name_indices([node.get("name") for node in observed_geometries], required)
        for node in observed_geometries:
            geometry = required[node.get("name")]
            mesh = node.find("geometry/mesh")
            relative = f"../../model/{Path(geometry['filename']).name}"
            if node.tag != geometry["kind"] or mesh.get("filename") != relative:
                raise ValueError("Derived geometry kind/reference changed")
            if (path.parent / relative).resolve() != Path(geometry["filename"]).resolve(strict=True):
                raise ValueError("Derived mesh reference does not resolve to its original input")
            t, rpy = _origin(node)
            for actual, wanted in ((t, geometry["origin_xyz"]), (rpy, geometry["origin_rpy"]),
                                   (_vector(mesh, "scale", "1 1 1"), geometry["scale"])):
                if not np.allclose(actual, wanted, atol=1e-14, rtol=0):
                    raise ValueError("Derived geometry transform/scale changed")
        if len(link) != len(required) + 1:
            raise ValueError("Unexpected derived link child")
    original_joints = {node.get("name"): node for node in _make_tree(source, expected).findall("joint")}
    for node in joints:
        if ET.tostring(node) != ET.tostring(original_joints[node.get("name")]):
            # Ignore pretty-print whitespace, but compare every joint field.
            def fields(element):
                return element.tag, element.attrib, [fields(child) for child in element]
            if fields(node) != fields(original_joints[node.get("name")]):
                raise ValueError(f"Derived joint changed: {node.get('name')}")
    return observed_bodies


def validate_derived(path, source=DEFAULT_SOURCE_URDF):
    """Read back a URDF against independently approved inputs and mass tensors."""
    path, source = Path(path).resolve(strict=True), Path(source).resolve(strict=True)
    expected = analyze_source(source)
    # Return the values actually read from the derived XML, after comparing them
    # to independent approved constants (never learn expectations from output).
    expected["bodies"] = _validate_tree(ET.parse(path).getroot(), path, source, expected)
    expected.update({"derived_path": str(path), "derived_sha256": hashlib.sha256(path.read_bytes()).hexdigest()})
    return expected


def generate_urdf(source, output):
    """Exclusively create a validated new file. Never overwrite or repair inputs."""
    source, output = Path(source).resolve(strict=True), Path(output).resolve()
    if output.suffix.lower() != ".urdf" or output == source or output.is_relative_to(source.parent / "model"):
        raise ValueError("Output must be a new derived URDF, never an original input")
    if output.exists():
        raise FileExistsError(output)
    expected = analyze_source(source)
    # Required ../../model paths must work independently of the working directory.
    if (output.parent / "../../model").resolve() != (source.parent / "model").resolve(strict=True):
        raise ValueError("Output must be in an asset version directory two levels below the source")
    root = _make_tree(source, expected)
    _validate_tree(root, output, source, expected)
    source_fingerprint(source)
    ET.indent(root, space="  ")
    payload = ET.tostring(root, encoding="utf-8", xml_declaration=True) + b"\n"
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("xb") as stream:
        stream.write(payload)
    source_fingerprint(source)
    return validate_derived(output, source)
